parser: "@babel/eslint-parser"
extends: [
  'eslint:recommended',
  'prettier',
  'plugin:react/recommended',
  'plugin:jsx-a11y/recommended',
  'plugin:prettier/recommended',
  'react-app',
  'react-app/jest'
]
plugins: ['react', 'prettier']
env:
  commonjs: true
  es6: true
  node: true
  browser: false
parserOptions:
  ecmaVersion: 2020
  ecmaFeatures:
    jsx: true
  sourceType: module
  requireConfigFile: false
globals:
  strapi: true
settings:
  import/parsers:
    espree:  ['.js', '.jsx']
  react:
    version: detect
rules:
  prettier/prettier: error
