parser: "@babel/eslint-parser"
extends: ['eslint:recommended', 'plugin:react/recommended', 'plugin:prettier/recommended']
plugins: 
  - react
  - prettier
  - jest
env:
  commonjs: true
  es6: true
  node: true
  browser: false
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
  requireConfigFile: false
globals:
  strapi: true
settings:
  import/parsers: 
    espree: 
      - .js
      - .jsx
  react: 
    version: detect