name: Deploy to github pages

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Cache dependencies
      #   uses: actions/cache@v2
      #   working-directory: ${{env.work-dir}}
      #   with:
      #     path: '**/node_modules'
      #     key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build
        working-directory: ./web
        run: |
          ls -lah
          yarn install --frozen-lockfile
          yarn test
          yarn build --if-present
          yarn export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out
